sudo: false
dist: trusty
language: nix
env:
 - TARGET=Geometry
 - TARGET=StarAgmlChecker
 - TARGET=StarAgmlLib
 - TARGET=StarAgmlUtil
 - TARGET=StarAgmlViewer
 - TARGET=RTS
 - TARGET=StAnalysisMaker
 - TARGET=StAnalysisUtilities
 - TARGET=StAssociationMaker
 - TARGET=StBFChain
 - TARGET=StBTofCalibMaker
 - TARGET=StBTofHitMaker
 - TARGET=StBTofMatchMaker
 - TARGET=StBTofMixerMaker
 - TARGET=StBTofPool
 - TARGET=StBTofSimMaker
 - TARGET=StBTofUtil
 - TARGET=StBbcSimulationMaker
 - TARGET=StBeamBackMaker
 - TARGET=StBichsel
 - TARGET=StChain
 - TARGET=StDAQMaker
 - TARGET=StDaqLib
 - TARGET=StDataFilterMaker
 - TARGET=StDbBroker
 - TARGET=StDbLib
 - TARGET=StDbUtilities
 - TARGET=StDetectorDbMaker
 - TARGET=StEEmcDbMaker
 - TARGET=StEEmcSimulatorMaker
 - TARGET=StEEmcUtil
 - TARGET=StEStructPool
 - TARGET=StEmbeddingUtilities
 - TARGET=StEmcADCtoEMaker
 - TARGET=StEmcCalibrationMaker
 - TARGET=StEmcMixerMaker
 - TARGET=StEmcPool
 - TARGET=StEmcRawMaker
 - TARGET=StEmcSimulatorMaker
 - TARGET=StEmcTriggerMaker
 - TARGET=StEmcUtil
 - TARGET=StEpcMaker
 - TARGET=StEpdDbMaker
 - TARGET=StEpdHitMaker
 - TARGET=StEpdUtil
 - TARGET=StEtrFastSimMaker
 - TARGET=StEvent
 - TARGET=StEventCompendiumMaker
 - TARGET=StEventMaker
 - TARGET=StEventUtilities
 - TARGET=StFgtA2CMaker
 - TARGET=StFgtClusterMaker
 - TARGET=StFgtDbMaker
 - TARGET=StFgtPointMaker
 - TARGET=StFgtRawMaker
 - TARGET=StFgtSimulatorMaker
 - TARGET=StFgtUtil
 - TARGET=StFlowAnalysisMaker
 - TARGET=StFmsDbMaker
 - TARGET=StFmsFastSimulatorMaker
 - TARGET=StFmsFpsMaker
 - TARGET=StFmsHitMaker
 - TARGET=StFmsPointMaker
 - TARGET=StFmsUtil
 - TARGET=StFpdMaker
 - TARGET=StFpsRawHitMaker
 - TARGET=StFtpcCalibMaker
 - TARGET=StFtpcClusterMaker
 - TARGET=StFtpcDriftMapMaker
 - TARGET=StFtpcMixerMaker
 - TARGET=StFtpcSlowSimMaker
 - TARGET=StFtpcTrackMaker
 - TARGET=StGammaMaker
 - TARGET=StGenericVertexMaker
 - TARGET=StGridCollector
 - TARGET=StHeavyTagMaker
 - TARGET=StHighPtTagsMaker
 - TARGET=StHitFilterMaker
 - TARGET=StHltMaker
 - TARGET=StIOMaker
 - TARGET=StIstClusterMaker
 - TARGET=StIstDbMaker
 - TARGET=StIstHitMaker
 - TARGET=StIstRawHitMaker
 - TARGET=StIstSimMaker
 - TARGET=StIstUtil
 - TARGET=StLaserAnalysisMaker
 - TARGET=StMCFilter
 - TARGET=StMagF
 - TARGET=StMcAnalysisMaker
 - TARGET=StMcEvent
 - TARGET=StMcEventMaker
 - TARGET=StMcQaMaker
 - TARGET=StMiniMcEvent
 - TARGET=StMiniMcMaker
 - TARGET=StMtdCalibMaker
 - TARGET=StMtdEvtFilterMaker
 - TARGET=StMtdHitMaker
 - TARGET=StMtdMatchMaker
 - TARGET=StMtdQAMaker
 - TARGET=StMtdSimMaker
 - TARGET=StMtdUtil
 - TARGET=StMuAnalysisMaker
 - TARGET=StMuDSTMaker
 - TARGET=StPCollTagMaker
 - TARGET=StPeCMaker
 - TARGET=StPicoDstMaker
 - TARGET=StPicoEvent
 - TARGET=StPidAmpMaker
 - TARGET=StPmdCalibrationMaker
 - TARGET=StPmdClusterMaker
 - TARGET=StPmdDiscriminatorMaker
 - TARGET=StPmdReadMaker
 - TARGET=StPmdSimulatorMaker
 - TARGET=StPmdUtil
 - TARGET=StPreEclMaker
 - TARGET=StPxlClusterMaker
 - TARGET=StPxlDbMaker
 - TARGET=StPxlHitMaker
 - TARGET=StPxlRawHitMaker
 - TARGET=StPxlSimMaker
 - TARGET=StPxlUtil
 - TARGET=StRichPool
 - TARGET=StRrsMaker
 - TARGET=StSecondaryVertexMaker
 - TARGET=StSpectraPool
 - TARGET=StSsdDaqMaker
 - TARGET=StSsdDbMaker
 - TARGET=StSsdFastSimMaker
 - TARGET=StSsdPointMaker
 - TARGET=StSsdSimulationMaker
 - TARGET=StSsdUtil
 - TARGET=StSstDaqMaker
 - TARGET=StSstPointMaker
 - TARGET=StSstUtil
 - TARGET=StStarLogger
 - TARGET=StStrangeMuDstMaker
 - TARGET=StStrangeTagsMaker
 - TARGET=StSvtCalibMaker
 - TARGET=StSvtClassLibrary
 - TARGET=StSvtClusterMaker
 - TARGET=StSvtDaqMaker
 - TARGET=StSvtDbMaker
 - TARGET=StSvtPool
 - TARGET=StSvtSeqAdjMaker
 - TARGET=StSvtSimulationMaker
 - TARGET=StTableUtilities
 - TARGET=StTagsMaker
 - TARGET=StTofCalibMaker
 - TARGET=StTofHitMaker
 - TARGET=StTofMaker
 - TARGET=StTofSimMaker
 - TARGET=StTofUtil
 - TARGET=StTofpMatchMaker
 - TARGET=StTofrMatchMaker
 - TARGET=StTpcDb
 - TARGET=StTpcHitMaker
 - TARGET=StTpcHitMoverMaker
 - TARGET=StTpcRSMaker
 - TARGET=StTreeMaker
 - TARGET=StTrgDatFileReader
 - TARGET=StTrgMaker
 - TARGET=StTriggerDataMaker
 - TARGET=StTriggerUtilities
 - TARGET=StTrsMaker
 - TARGET=StUtilities
 - TARGET=StVpdCalibMaker
 - TARGET=StVpdSimMaker
 - TARGET=StXTrakMaker
 - TARGET=StZdcVertexMaker
 - TARGET=St_QA_Maker
 - TARGET=St_TLA_Maker
 - TARGET=St_base
 - TARGET=St_baseTest
 - TARGET=St_ctf_Maker
 - TARGET=St_db_Maker
 - TARGET=St_emc_Maker
 - TARGET=St_geant_Maker
 - TARGET=St_pp2pp_Maker
 - TARGET=St_sdm_Maker
 - TARGET=St_srs_Maker
 - TARGET=St_tcl_Maker
 - TARGET=St_trg_Maker
 - TARGET=Star2Root
 - TARGET=StarClassLibrary
 - TARGET=StarMagField
 - TARGET=StarRoot
 - TARGET=StdEdxY2Maker
 - TARGET=Sti
 - TARGET=StiCA
 - TARGET=StiIst
 - TARGET=StiMaker
 - TARGET=StiPxl
 - TARGET=StiRnD
 - TARGET=StiSsd
 - TARGET=StiSvt
 - TARGET=StiTpc
 - TARGET=StiUtilities
 - TARGET=Stl3RawReaderMaker
 - TARGET=Stl3Util
# Travis says: Build matrix exceeds 200 jobs
# - TARGET=Stv
# - TARGET=StvMaker
# - TARGET=StvSeed
# - TARGET=StvUtil
# - TARGET=TPCCATracker
before_script:
# download precompiled deps. will timeout if no dns/connect/read in 20 seconds and wait 5 seconds before trying again
 - wget --retry-connrefused --timeout=20 --waitretry=5 --tries=20 http://aspid.ru/~dump/55i5vnakyd2bjpdnx020scx58ahlxxhg-star-soft.drv-closure.nar
 - nix-store --import < *.nar
script: nix-build .travis/default.nix -I star-nix=https://github.com/veprbl/star-nix/archive/6d2be9f816c26fd770b31942a08baa89271f9bfb.tar.gz --arg nixpkgs "import (builtins.fetchTarball https://github.com/NixOS/nixpkgs/tarball/120b013e0c082d58a5712cde0a7371ae8b25a601) {}" --argstr target $TARGET --cores 2
